# Generated by Django 3.2.7 on 2021-09-15 16:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0078_auto_20210214_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='razdel',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.DeleteModel(
            name='Razdel',
        ),
    ]
