# Generated by Django 3.2.7 on 2021-09-15 16:47

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MDShop', '0079_auto_20210915_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartphone',
            options={'ordering': ['-id'], 'verbose_name': 'Смартфон', 'verbose_name_plural': 'Смартфоны'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Стандарт защиты от пыли и влаги'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Стандарт защиты от пыли и влаги'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Стандарт защиты от пыли и влаги'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Стандарт защиты от пыли и влаги'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Стандарт защиты от пыли и влаги'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя категория'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='genres',
            field=models.ManyToManyField(to='MDShop.Genre', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='1.Изображения для слайдера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='2.Изображения для слайдера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='3.Изображения для слайдера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='4.Изображения для слайдера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='5.Изображения для слайдера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='6.Изображения для слайдера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
