# Generated by Django 3.2.7 on 2021-09-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MDShop', '0080_auto_20210915_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populargoods',
            name='top1',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-id'], 'verbose_name': 'Адрес доставка', 'verbose_name_plural': 'Адрес доставки'},
        ),
        migrations.AlterModelOptions(
            name='customerlike',
            options={'ordering': ['-id'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Эл. адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='addressCustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer', verbose_name='Покупателя'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=30, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cтрана'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='house',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='index',
            field=models.CharField(blank=True, max_length=30, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='town',
            field=models.CharField(blank=True, max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customerlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='customerlike',
            name='likeCustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='customerlike',
            name='likeNEW',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.smartphone', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='customerlike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=160, unique=True, verbose_name='URL'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PopularGoods',
        ),
    ]
