# Generated by Django 3.2.7 on 2021-09-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0081_auto_20210915_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customeraddress', verbose_name='Адрес покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderCustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer', verbose_name='Покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='smartphone',
            field=models.ManyToManyField(to='MDShop.smartphone', verbose_name='Смартфон'),
        ),
    ]
